id: I3F73F9BF
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 14:52:46.983708
last_modified: 2023-02-08 14:52:46.983844
source_metadata:
  title: 'PP: Aṣṭasāhasrikā Prajñāpāramitā'
  language: zh
bases:
  '2244':
    base_file: 2244.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
